---
# main.yml for software role

- name: Update apt-get cache
  become: True
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"

- name: Update repositories cache and install common packages
  become: True
  apt:
    name: "{{ item }}"
    dpkg_options: 'force-confold,force-confdef'
  with_items:
    - iputils-ping
    - inetutils-tools
    - tmux
    - mc
    - atop
    - nload
    - sudo
    - vim
    - wget
    - telnet
    - git
    - mtr
    - apt-file
    - man
    - gettext
    - bind9-host
    - traceroute
    - elinks
    - lynx
    - elinks
    - iotop
    - ncdu
    - rsync
    - apt-file
    - python-pip
    - python3-pip
    - software-properties-common
  tags:
    - install_pkg

- name: Include apt-file configuration
  include: "apt-file.yml"
  tags:
    - environment
