---
# Role partition
# http://www.googlinux.com/ansible-2-3-new-modules/index.html

- name: Get partiotion info
  parted: device={{ additional_disk }} unit=MiB state=info
  register: additional_disk_info

- name: Debug device_stat
  debug:
    var: additional_disk_info

- name: Create partition
  parted:
    device: "{{ additional_disk }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
    - "{{ additional_disk_info.partitions }}"
  when: not item.num

- name: Format device
  filesystem:
    fstype: ext4
    dev: "{{ additional_disk }}"
    # opts: -cc   # Check for diskerros by badblocks
    # badblocks -b 4096 -X -s -w /dev/xvdh 13107199

- name: Mount data for docker
  mount: 
    state: mounted
    src: "{{ additional_disk }}"
    name: "{{ additional_disk_mount }}"
    fstype: "ext4"
    opts: defaults,noatime,nodiratime
    dump: 0
    passno: 0




