---
# plugins.yml

# - name: Wait for Jenkins to start up
#   uri:
#     url: http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}
#     status_code: 200
#     timeout: 5
#   register: jenkins_service_status
#   # Keep trying for 5 mins in 5 sec intervals
#   retries: 60
#   delay: 5
#   until: >
#      'status' in jenkins_service_status and
#      jenkins_service_status['status'] == 200

- name: "wait for ABC to come up"
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/login"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1

- name: Install Jenkins plugins using password.
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_data_container_name }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_user }}"
    state: "{{ jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_admin_password != ""
  tags:
    - jenkins_plugins
  notify: Restart above container
