---
# Playbook for jenkins host

- hosts: all
  become: True

  vars:
    additional_disk: "/dev/xvdh"
    additional_disk_mount: "/data"
    docker_data_dir: "/data/docker-data"

  roles:
    - { role: software, tags: ['software'] }
    - { role: partition, tags: ['partition'] }
    # - { role: dochang.docker, tags: ['docker'] }
    # - { role: jenkins, tags: ['jenkins'] }
