---
# Playbook for jenkins host

# - hosts: all
- hosts: all
  become: True

  vars:
    additional_disk: "/dev/xvdh"
    additional_disk_mount: "/data"
    docker_data_dir: "/data/docker-data"
    jenkins_admin_username: admin
    jenkins_admin_password: admin321

  roles:
    - { role: software, tags: ['software'] }
    - { role: partition, tags: ['partition'] }
    - { role: dochang.docker, tags: ['docker'] }
    - { role: jenkins, tags: ['jenkins'] }
